/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GamePlayersPlayerIdImport } from './routes/game/players/$playerId'

// Create Virtual Routes

const RulesLazyImport = createFileRoute('/rules')()
const IndexLazyImport = createFileRoute('/')()
const GameIndexLazyImport = createFileRoute('/game/')()
const GamePlayersIndexLazyImport = createFileRoute('/game/players/')()

// Create/Update Routes

const RulesLazyRoute = RulesLazyImport.update({
  path: '/rules',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/rules.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GameIndexLazyRoute = GameIndexLazyImport.update({
  path: '/game/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/game/index.lazy').then((d) => d.Route))

const GamePlayersIndexLazyRoute = GamePlayersIndexLazyImport.update({
  path: '/game/players/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/game/players/index.lazy').then((d) => d.Route),
)

const GamePlayersPlayerIdRoute = GamePlayersPlayerIdImport.update({
  path: '/game/players/$playerId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/rules': {
      preLoaderRoute: typeof RulesLazyImport
      parentRoute: typeof rootRoute
    }
    '/game/': {
      preLoaderRoute: typeof GameIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/game/players/$playerId': {
      preLoaderRoute: typeof GamePlayersPlayerIdImport
      parentRoute: typeof rootRoute
    }
    '/game/players/': {
      preLoaderRoute: typeof GamePlayersIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  RulesLazyRoute,
  GameIndexLazyRoute,
  GamePlayersPlayerIdRoute,
  GamePlayersIndexLazyRoute,
])

/* prettier-ignore-end */
